stages:
  - build
  - test
  - lint

variables:
  NODE_IMAGE: 'node:20'

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

before_script:
  - npm install -g npm@latest

build_frontend:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/.next
      - frontend/out

build_backend:
  stage: build
  image: $NODE_IMAGE
  script:
    - cd backend
    - npm install
    - npm run build
  artifacts:
    paths:
      - backend/dist

lint_frontend:
  stage: lint
  image: $NODE_IMAGE
  script:
    - cd frontend
    - npm run lint

lint_backend:
  stage: lint
  image: $NODE_IMAGE
  script:
    - cd backend
    - npm run lint

test_frontend:
  stage: test
  image: $NODE_IMAGE
  script:
    - cd frontend
    - npm install
    - npm run test -- --coverage
  artifacts:
    reports:
      cobertura: frontend/coverage/cobertura-coverage.xml
    paths:
      - frontend/coverage

test_backend:
  stage: test
  image: $NODE_IMAGE
  script:
    - cd backend
    - npm install
    - npm run test:cov
  artifacts:
    reports:
      cobertura: backend/coverage/cobertura-coverage.xml
    paths:
      - backend/coverage

test_e2e:
  stage: test
  image: $NODE_IMAGE
  script:
    - cd backend
    - npm install
    - npm run test:e2e
