services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: always
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/newsdb

  frontend:
    build: ./frontend
    restart: always
    container_name: frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000/api

volumes:
  mongo_data:
